services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: vendora-backend
    env_file:
      - ./.env
    expose:
      - "8000"
    environment:
      NODE_ENV: production
      PORT: 8000
      FRONTEND_URL: http://3.105.71.141:80
      API_URL: http://3.105.71.141:8000
    networks:
      - vendora-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vendora-frontend
    expose:
      - "80"
    depends_on:
      - backend
    networks:
      - vendora-network
    restart: unless-stopped

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: vendora-nginx:latest
    container_name: vendora-nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - vendora-network
    restart: unless-stopped

networks:
  vendora-network:
    driver: bridge
