---
- name: Configure Nginx
  hosts: production
  become: true

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Deploy nginx config
      copy:
        src: ../../nginx/nginx.conf
        dest: /etc/nginx/nginx.conf
        backup: yes

    - name: Validate nginx config
      command: nginx -t
      register: nginx_test
      changed_when: false

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
        enabled: yes
      when: nginx_test.rc == 0
